# Generated by Django 3.1.5 on 2021-01-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0004_auto_20210116_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('seat_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('passenger_name', models.CharField(max_length=50)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule')),
            ],
            options={
                'unique_together': {('schedule', 'seat_number', 'seat_code')},
            },
        ),
    ]
