# Generated by Django 3.1.5 on 2021-01-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='passenger_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
