# Generated by Django 3.1.5 on 2021-01-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_seat_passenger_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='passenger_email',
            field=models.CharField(max_length=50),
        ),
    ]
