# Generated by Django 3.1.5 on 2021-01-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0003_auto_20210116_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='passenger_email',
            field=models.EmailField(max_length=254),
        ),
    ]
