# Generated by Django 3.1.5 on 2021-01-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20210116_1140'),
        ('seats', '0004_auto_20210116_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('schedule', 'seat_number')},
        ),
    ]
