# Generated by Django 3.1.5 on 2021-01-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='places.place')),
                ('place_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='places.place')),
            ],
        ),
    ]
