# Generated by Django 3.1.5 on 2021-01-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('routes', '0004_auto_20210115_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='place_destination',
        ),
        migrations.AlterField(
            model_name='route',
            name='place_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.place'),
        ),
    ]
