# Generated by Django 3.1.5 on 2021-01-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('routes', '0007_auto_20210115_1711'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('place_origin', 'place_destination')},
        ),
    ]
