# Generated by Django 3.1.5 on 2021-01-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(blank=True, default=10, null=True)),
                ('operative', models.BooleanField(default=True)),
            ],
        ),
    ]
