# Generated by Django 3.1.5 on 2021-01-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20210115_1711'),
        ('buses', '0002_bus_user'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule',
            new_name='schedule_time',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('route', 'bus', 'schedule_time')},
        ),
    ]
