# Generated by Django 3.1.5 on 2021-01-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20210115_1711'),
        ('buses', '0002_bus_user'),
        ('schedules', '0003_auto_20210115_1725'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('route', 'bus', 'schedule_time')},
        ),
    ]
